### PR TITLE
Add start fail modal in get-started-screen.tsx

### PR DESCRIPTION
**Pull request by Nodirbek75**
Resolve the issue [#92](https://github.com/lnflash/flash-mobile/issues/92)

### CODE REVIEW

**Comment by islandbitcoin** [comment]
looks good so far, the words are correct. Only one UX problem, it spins for a long time after pressing "Explore wallet", I think it should go directly to zero balances for both wallets, and not initialize the breez-sdk

Screenshot 2024-02-19 at 10 39 38 AM

**Comment by islandbitcoin** [comment]
yes, remove it for explore wallet, but show a zero balance for it even though it is not initialized yet

**Comment by islandbitcoin** [comment]
in explore wallet, when I click on "receive" it should pop up a modal at the bottom giving the user the option to log in.
That is no longer showing up, I think it needs to show up, and give them the start button.
Screenshot 2024-02-19 at 11 04 38 AM

**Comment by islandbitcoin** [comment]
yes. Here is the blink receive screen in "explore wallet" mode:

IMG_0ACE4A7D60AC-1

**Comment by Nodirbek75** [comment]
@islandbitcoin implemented the changes. Please test it out

**Comment by islandbitcoin** [comment]
> @islandbitcoin implemented the changes. Please test it out

Almost there! one more thing you missed, lets make it the "start" button instead of the blink "login/create account" button".
You can also just send them back to the start screen if that is a better UX flow.

IMG_0ACE4A7D60AC-1

**Comment by islandbitcoin** [comment]
> @islandbitcoin How should I change wordings on the bottom modal?

No changes to the wording. Just make the button take the user back to the start screen

**Comment by islandbitcoin** [comment]
Screenshot 2024-02-19 at 2 19 19 PM

this looks great! Approved

**Review by islandbitcoin — APPROVED** [review]
LGTM

**Pull request merged**
