### PR TITLE
Implement nfc feature for breez BTC wallet and show insufficient balance error if funds not enough in the nfc card

### PR DESCRIPTION
**Pull request by Nodirbek75**
- [ ]  Test if nfc for breez BTC wallet is working as expected
- [x]  Test with ibex USD wallet and check if you getting full err or message

### CODE REVIEW

**Comment by islandbitcoin** [comment]
the messages need to be more readable.
currently I see "Payment request was not within bounds"
and "Generic: Generic: Amount is bigger than the maximum allowed by the LNURL-withdraw endpoint" 

Both of these messages need to be shorter and easier to read. 

"Insufficient Funds"

**Comment by Nodirbek75** [comment]
It is not possible to detect if the error is due to insufficient funds. For example, the image below shows errors from LNbits and BTCPay Server. Both have different reasons but the same status, 'Error'.

I could show an 'Insufficient Funds' error message for all errors, but I don't think that is the best practice.

Screenshot 2024-07-31 at 2 45 55 PM

Screenshot 2024-07-31 at 2 46 14 PM

**Comment by islandbitcoin** [comment]
> It is not possible to detect if the error is due to insufficient funds. For example, the image below shows errors from LNbits and BTCPay Server. Both have different reasons but the same status, 'Error'.
> 
> I could show an 'Insufficient Funds' error message for all errors, but I don't think that is the best practice.
> 
> Screenshot 2024-07-31 at 2 45 55 PM Screenshot 2024-07-31 at 2 46 14 PM

would this work?

```

      if (result.ok) {
        if (lnurlResponse?.status?.toLowerCase() !== "ok") {
          console.error(lnurlResponse, "error with redeeming")
          Alert.alert(lnurlResponse.reason || LL.RedeemBitcoinScreen.redeemingError())
        }
      } else if (
        (lnurlResponse.reason && lnurlResponse.reason.includes("not within bounds")) ||
        lnurlResponse.reason.includes("Amount is bigger than the maximum")
      ) {
        Alert.alert("Payment Failed: Insufficient Funds")
      } else {
        Alert.alert(lnurlResponse.reason || LL.RedeemBitcoinScreen.submissionError())
      }
```

**Comment by Nodirbek75** [comment]
> > It is not possible to detect if the error is due to insufficient funds. For example, the image below shows errors from LNbits and BTCPay Server. Both have different reasons but the same status, 'Error'.
> > I could show an 'Insufficient Funds' error message for all errors, but I don't think that is the best practice.
> > Screenshot 2024-07-31 at 2 45 55 PM Screenshot 2024-07-31 at 2 46 14 PM
> 
> would this work?
> 
> ```
> 
>       if (result.ok) {
>         if (lnurlResponse?.status?.toLowerCase() !== "ok") {
>           console.error(lnurlResponse, "error with redeeming")
>           Alert.alert(lnurlResponse.reason || LL.RedeemBitcoinScreen.redeemingError())
>         }
>       } else if (
>         (lnurlResponse.reason && lnurlResponse.reason.includes("not within bounds")) ||
>         lnurlResponse.reason.includes("Amount is bigger than the maximum")
>       ) {
>         Alert.alert("Payment Failed: Insufficient Funds")
>       } else {
>         Alert.alert(lnurlResponse.reason || LL.RedeemBitcoinScreen.submissionError())
>       }
> ```

It works if all other servers return this kind of error. If they return smth else, it won't work.
For example: Lnbits returns "Payment failed - Insufficient balance" and it won't work for it. I should add another check for this case

**Comment by Nodirbek75** [comment]
Or for now do you want me to put these 2 checks?

**Comment by islandbitcoin** [comment]
> > > It is not possible to detect if the error is due to insufficient funds. For example, the image below shows errors from LNbits and BTCPay Server. Both have different reasons but the same status, 'Error'.
> > > I could show an 'Insufficient Funds' error message for all errors, but I don't think that is the best practice.
> > > Screenshot 2024-07-31 at 2 45 55 PM Screenshot 2024-07-31 at 2 46 14 PM
> > 
> > 
> > would this work?
> > ```
> > 
> >       if (result.ok) {
> >         if (lnurlResponse?.status?.toLowerCase() !== "ok") {
> >           console.error(lnurlResponse, "error with redeeming")
> >           Alert.alert(lnurlResponse.reason || LL.RedeemBitcoinScreen.redeemingError())
> >         }
> >       } else if (
> >         (lnurlResponse.reason && lnurlResponse.reason.includes("not within bounds")) ||
> >         lnurlResponse.reason.includes("Amount is bigger than the maximum")
> >       ) {
> >         Alert.alert("Payment Failed: Insufficient Funds")
> >       } else {
> >         Alert.alert(lnurlResponse.reason || LL.RedeemBitcoinScreen.submissionError())
> >       }
> > ```
> 
> It works if all other servers return this kind of error. If they return smth else, it won't work. For example: Lnbits returns "Payment failed - Insufficient balance" and it won't work for it. I should add another check for this case

Add another check for this case. We can always add more checks in the future.
This will give a better user experience for MVP.

**Comment by islandbitcoin** [comment]
its working now.

**Review by islandbitcoin — APPROVED** [review]
ACK

**Pull request merged**
