### PR TITLE
Show destination field for only username and lnurl payment types. Show memo field if it is editable

### PR DESCRIPTION
**Pull request by Nodirbek75**
[#198](https://github.com/lnflash/flash-mobile/issues/198)

### CODE REVIEW

**Comment by islandbitcoin** [comment]
the confirm screen needs to be changed too... 


Screenshot 2024-07-31 at 12 15 50 AM

**Comment by Nodirbek75** [comment]
@islandbitcoin That's what I asked here: https://github.com/lnflash/flash-mobile/issues/198#issuecomment-2259002253

**Comment by Nodirbek75** [comment]
So, destination should be visible for only lnurl and username? 
And memo should be hidden because it is not editable in this screen?

**Comment by islandbitcoin** [comment]
> So, destination should be visible for only lnurl and username? And memo should be hidden because it is not editable in this screen?

for the Send screens; we want the remove anything that may be confusing to the regular non-bitcoin user. i will need you to look at the screen and make that determination
so for the confirmation screen, if it is showing an lnurl string, that should be hidden. and if the memo screen is just showing a generated ID, that should be hidden too
but if the destination field is showing a flash username or flash lightning address, that is human readable and can remain visible

**Review by islandbitcoin — APPROVED** [review]
ACK

**Pull request merged**
