### PR TITLE
Change breez-sdk-greenlight to breez-sdk-liquid

### PR DESCRIPTION
**Pull request by Nodirbek75**
- [x] The "switch to advanced mode" setting was still hidden in the settings screen. Unhide
- [x] When first clicking on "receive" after enabling the bitcoin wallet, modal pops up asking to choose default wallet. If Bitcoin wallet is selected, it goes to the Bitcoin receive screen without asking to enter an amount. (I cannot reproduce this on the simulator)
- [ ] Failed swap from USD to BTC for 100%. "An unexpected error occured. Please try again later"
- [x]  When i completed the recovery process and pressed "Done", it did not take me back to the home screen. When i backed out to the home sceen, I had to pull to refresh to see my updated balance

### CODE REVIEW

**Comment by islandbitcoin** [comment]
I'm still able to press next, even though the error message is showing. This should be grayed out.

Screenshot 2024-09-09 at 1 45 30 PM

**Comment by islandbitcoin** [comment]
Still getting this message "There may be a small fee for routing" But we should be able to show this fee with LiquidSDK now

Screenshot 2024-09-09 at 1 50 59 PM

**Comment by Nodirbek75** [comment]
> Going from BTC wallet to USD Wallet, I'm still getting this message "There may be a small fee for routing" But we should be able to show this fee with LiquidSDK now
> 
> Screenshot 2024-09-09 at 1 50 59 PM

@islandbitcoin liquidSDK doesn't yet have a method to calculate the fee when sending to a Lightning address. I asked them in [slack](https://flash-qwj9494.slack.com/archives/C05HYBUS4E5/p1724869029518859) and created an issue in [github](https://github.com/breez/breez-sdk-liquid/issues/468) for them.

**Review by islandbitcoin — APPROVED** [review]
ACK

**Pull request merged**
