### PR TITLE
Fix event emitter

### PR DESCRIPTION
**Pull request by Nodirbek75**

### CODE REVIEW

**Comment by islandbitcoin** [comment]
can you remove the addLogListenerBreezSDK()? its spamming the logs:

https://github.com/lnflash/flash-mobile/blob/401a20a7ac7a6f98f4f78f882bc55a2da745ea67/app/components/wallet-overview/wallet-overview.tsx#L98C25-L98C25

**Comment by Nodirbek75** [comment]
@islandbitcoin removed addLogListenerBreezSDK()

**Comment by Nodirbek75** [comment]
I reverted back removing addLogListenerBreezSDK() commits because I saw you already removed in another branch

**Review by islandbitcoin — APPROVED** [review]
ACK

**Pull request merged**
