### PR TITLE
Beginner and Advance mode

### PR DESCRIPTION
**Pull request by Nodirbek75**

### CODE REVIEW

**Comment by islandbitcoin** [comment]
Feedback/Changes:

Beginner Mode:
- Receive Screen: Change "Receive via Lightning" to just "Receive"
- Send Screen: Change "Send Bitcoin" to just "Send"

Advanced Mode:
- Change "Switch to **Advance** Mode" to "Switch to **Advanced** Mode"
- When switching to Advanced mode, bring the user back to the Home Screen after switching.
- The dropdown for Cash/Bitcoin is too low on the screen, it feels disconnected.
- Same for the Lightning/Paycode/Onchain dropdown. the options should be near the dropdown button.
- On both dropdowns, the dropdown arrows are reversed. They should be pointing down.

Misc Bugs: 
- Missing Tx History without refresh: Transaction History screen says no transactions to show, but I see 3 transactions on the home screen. When I do a pull to refresh, then the 3 transactions show up in the transaction history screen.
- Secondary currency display remains on USD setting: When I change the display currency from USD to JMD, a secondary amount shows up on the Home Screen in wallet overview. But when I change it back from JMD to USD, the secondary amount does not disappear.

**Comment by Nodirbek75** [comment]
@islandbitcoin Yes, dropdown is bottom of the screen because I'm using bottom sheet not dropdown. 
It is shown on the figma and I thought we agreed to use bottom sheet. I think on mobile design mostly bottom sheet is used not dropdown. Dropdown is for more web design I think. 

Screenshot 2024-04-29 at 12 33 32 PM

**Comment by islandbitcoin** [comment]
In figma, the button is near the bottom sheet, so when you press it so it feels more connected.

**Review by islandbitcoin — APPROVED** [review]
ACK

**Pull request merged**
