### PR TITLE
fix "USD Balance and USD Transaction History calculation variance"

### PR DESCRIPTION
**Pull request by Nodirbek75**
- Fix 'USD Balance and USD Transaction History calculation variance' issue
- Remove 'Wallet powered by Galoy' text on the settings screen

### CODE REVIEW

**Comment by islandbitcoin** [comment]
I see you removed the "Wallet powered by Galoy" but didn't replace it with anything.
We spoke about replacing it with "Made in Jamaica" on standup.

**Comment by islandbitcoin** [comment]
Based on Joe's comment during standup, what happens when two transactions add up:

$0.046 + $0.046 = $0.092 

The UI will show:
$0.04 + $0.04 = $0.09

We will be showing incorrect math to the end-user

**Comment by Nodirbek75** [comment]
> Based on Joe's comment during standup, what happens when two transactions add up:
> 
> $0.046 + $0.046 = $0.092
> 
> The UI will show: $0.04 + $0.04 = $0.09
> 
> We will be showing incorrect math to the end-user

Yes, that's right $0.09 will be shown to the end-user. 9 cents is the value front-end receives from server.
That's why I was suggesting to show 3 decimal numbers maximum in the UI

**Comment by islandbitcoin** [comment]
how is Galoy handling this?

**Comment by Nodirbek75** [comment]
> how is Galoy handling this?

Galoy is showing $0.08 on the balance. Need to check how they are handling on the backend.
Because the balance coming from backend as integer cents not with decimal numbers.

**Comment by islandbitcoin** [comment]
where did we land on this? 

I think we said we will just show 0.08, and make sure the full decimal places are displayed on the CSV export, and all calculations are being done with the full decimal places.

**Comment by Nodirbek75** [comment]
You mean $0.09? Because on the wallet overview 0.09 will be shown which amount comes from server.
And yes, csv file shows all the decimal places

**Review by islandbitcoin — APPROVED** [review]
ACK

**Comment by islandbitcoin** [comment]
Ready to merge

**Pull request merged**
