### PR TITLE
add welcome screens and help icon

### PR DESCRIPTION
**Pull request by islandbitcoin**
Help icon will show only once, and will disappear when dismissed.

### CODE REVIEW

**Comment by islandbitcoin** [comment]
> @islandbitcoin Shouldn't we put welcome screen in the first screen instead of get-started-screen?

I thought about it... and decided no.
I wanted to get the user to the Home Screen as quickly as possible. 
Blink used to have the welcome screen in the first screen and then they removed it, based on user feedback.

**Comment by islandbitcoin** [comment]
> And also, we should use "react-native-reanimated-carousel" or "react-native-snap-carousel" for better performance and better UI

I cannot get any of them to work on Android with the swipe functionality. Do you know why?

**Comment by islandbitcoin** [comment]
Added a help icon on the getStarted screen, and changed to using react-native-reanimated-carousel.

**Review by Nodirbek75 — COMMENTED** [review]
Should we remove question icon button on the home screen or keep it?

**Comment by islandbitcoin** [comment]
> Should we remove question icon button on the home screen or keep it?

it's a one time press so i want to keep it.

**Pull request merged**
