### PR TITLE
Update transaction memo

### PR DESCRIPTION
**Pull request by Nodirbek75**

### CODE REVIEW

**Comment by islandbitcoin** [comment]
the USD wallet wording is fixed.
the BTC wallet wording is still incorrect 

Screenshot 2024-03-28 at 8 19 51 AM

**Comment by islandbitcoin** [comment]
this should say "Received from" not "Received to"


Screenshot 2024-03-28 at 8 36 33 AM

**Comment by Nodirbek75** [comment]
@islandbitcoin 
Updated transaction memo to Received and Sent.
Change Scan to Scan QR

**Review by islandbitcoin — APPROVED** [review]
Labels are correct on memo and scan button. 
ACK

**Pull request merged**
