### PR TITLE
Fix lnurlPay comment

### PR DESCRIPTION
**Pull request by Nodirbek75**

### CODE REVIEW

**Comment by islandbitcoin** [comment]
I still cannot get past this error message. The goal is to make the comment visible and editable on this screen.

IMG_3315380F9BE6-1

**Comment by Nodirbek75** [comment]
> I'm entering in a lightning address ([chat@bitcorn.io](mailto:chat@bitcorn.io)), and I still cannot get past this error message. The goal is to make the comment visible and editable on this screen.
> 
> IMG_3315380F9BE6-1

This PR fixes this issue: https://github.com/lnflash/flash-mobile/issues/261

Not this one: https://github.com/lnflash/flash-mobile/issues/262

**Comment by islandbitcoin** [comment]
ah ok.... thanks. 

ACK

**Review by islandbitcoin — APPROVED** [review]
ACK

**Pull request merged**
