### PR TITLE
For BTC wallet receive on Lightning invoice, force users to enter amount before generating Invoice

### PR DESCRIPTION
**Pull request by Nodirbek75**
#146

### CODE REVIEW

**Comment by islandbitcoin** [comment]
I cannot click on the X to cancel and go back to the Home Screen.
Screenshot 2024-04-12 at 4 19 43 PM

**Comment by Nodirbek75** [comment]
> I cannot click on the X to cancel and go back to the Home Screen. Screenshot 2024-04-12 at 4 19 43 PM

Fixed and pushed the changes. Please test it out.

**Comment by islandbitcoin** [comment]
Feedback:

- When clicking receive on BTC wallet with a zero balance, I'm now getting a new error when going back to the Home Screen:
```
Error fetching breezInvoice: [Error: Invalid amount: Amount should be more than the minimum fees 9650666 msat, but is 7737000 msat]
 ERROR  [Error: Not a proper lightning payment request]
```
Screenshot 2024-04-15 at 11 29 54 AM

**Comment by islandbitcoin** [comment]
cannot reproduce. ACK

**Review by islandbitcoin — APPROVED** [review]
ACK

**Pull request merged**
