### PR TITLE
Feature/seed phrase backup

### PR DESCRIPTION
**Pull request by Nodirbek75**

### CODE REVIEW

**Comment by islandbitcoin** [comment]
Looks great so far!!
Feedback:
- Grey out the "Backup to iCloud" and "Backup to Google Drive" and put "coming soon" or something to let users know that those buttons are not working yet. 
- On the double-check screen,  put "Yes, it's that important" on a separate line and in bold.
- After it's complete, and I go back to the settings screen, let them click the button, and after authenticating with pin or biometrics again let them see the seed phrase.


Food for thought:
- I'm thinking we add a "Backup to Flash" option, where we hold their keys and let them create a password to decrypt it. Let's consider this after MVP.

**Comment by islandbitcoin** [comment]
testing on the Samsung S23, there is no scroll to see the buttons below:
Screenshot 2024-02-01 at 1 41 57 PM

**Comment by islandbitcoin** [comment]
I probably shouldn't have posted the seed phrase on a public GitHub lol
Its an empty wallet on the sim, I'll wipe it now

**Comment by Nodirbek75** [comment]
> Looks great so far!! Feedback:
> 
> * Grey out the "Backup to iCloud" and "Backup to Google Drive" and put "coming soon" or something to let users know that those buttons are not working yet.
> * On the double-check screen,  put "Yes, it's that important" on a separate line and in bold.
> * After it's complete, and I go back to the settings screen, let them click the button, and after authenticating with pin or biometrics again let them see the seed phrase.
> 
> Food for thought:
> 
> * I'm thinking we add a "Backup to Flash" option, where we hold their keys and let them create a password to decrypt it. Let's consider this after MVP.



> Looks great so far!! Feedback:
> 
> * Grey out the "Backup to iCloud" and "Backup to Google Drive" and put "coming soon" or something to let users know that those buttons are not working yet.
> * On the double-check screen,  put "Yes, it's that important" on a separate line and in bold.
> * After it's complete, and I go back to the settings screen, let them click the button, and after authenticating with pin or biometrics again let them see the seed phrase.
> 
> Food for thought:
> 
> * I'm thinking we add a "Backup to Flash" option, where we hold their keys and let them create a password to decrypt it. Let's consider this after MVP.

1. Can't we just remove "Backup to iCloud" and "Backup to Google Drive" buttons for now?

**Comment by islandbitcoin** [comment]
> > Looks great so far!! Feedback:
> > 
> > * Grey out the "Backup to iCloud" and "Backup to Google Drive" and put "coming soon" or something to let users know that those buttons are not working yet.
> > * On the double-check screen,  put "Yes, it's that important" on a separate line and in bold.
> > * After it's complete, and I go back to the settings screen, let them click the button, and after authenticating with pin or biometrics again let them see the seed phrase.
> > 
> > Food for thought:
> > 
> > * I'm thinking we add a "Backup to Flash" option, where we hold their keys and let them create a password to decrypt it. Let's consider this after MVP.
> 
> 1. Can't we just remove "Backup to iCloud" and "Backup to Google Drive" buttons for now?

yes.

**Comment by Nodirbek75** [comment]
@islandbitcoin implemented feedback changes. Please, test it out

**Comment by islandbitcoin** [comment]
Feedback:
- I'm still not able to scroll down on the screen with the words, the Verify button is half hidden (using Samsung galaxy S23 API 33 device simulator)
- Double check screen looks great!
- the "show me again" button should say "Try again"
- I cannot progress from the verify screen because I cannot see the button below the "Show me again" button and I cannot scroll (see screenshot)
Screenshot 2024-02-02 at 1 47 49 PM

**Comment by islandbitcoin** [comment]
tested it on the Pixel 7 Pro so I could get past the verify screen. 
I like the "reveal recovery phrase" flow. does this ask the user to enter their pin/biometrics?

**Comment by Nodirbek75** [comment]
@islandbitcoin Yes, it will ask if it is turned on in the app security settings.

**Comment by islandbitcoin** [comment]
Looks great!

**Review by islandbitcoin — APPROVED** [review]
ACK

**Pull request merged**
